### ISSUE TITLE
Web Interface [Feature Request]

### ISSUE THREAD

**Issue by Rimers** [j-e-k/poketrainer#105]
A way to prioritize Eggs to incubate, eg first all 10km, then 5 then 2.

Show when a Fort was last spun status and if possible make a log of what was gained from the spin.
The log ought to be available from a separate page or popup not to make a mess of the main web page.

Show current position (when page is updated/refreshed) and position where we are going to but not necessarily the route we plan to take.

Edit: 
Sorry if i make several requests in one, I am new to this and I just saw that most other requests are one feature in each request.

**Comment by Abdess** [comment]
It could be also interesting to see all Pokémons around in the map and the ability to select a place to go to catch a specific Pokémon. :)

**Comment by j-e-k** [comment]
I don't really do much (any) web dev so I was hoping to have someone colab and take over that front. I will dump more JSON to the page and hopefully someone can throw together some javascript...any takers?

**Comment by beeedy** [comment]
Want to throw in my 2c, the ability to go to a generic interface with a dropdown of all found accounts rather than having to enter url's would be amazing

**Comment by Jay1** [comment]
So far the map is updated only with the dump file. I know there is a discussion about websocket and streaming the coords on every heartbeat. In a couple of days when @j-e-k and friends are done with #54 it would be possible to "input" coords by clicking the map. Right now, what @Abdess suggest is really hard because the bot is moving a lot in between every dump in the file, so it would softban instantly if we tried to move it from there. Worst case scenario we could tell the bot : " right I know you're far away now, but could you move in that direction during the next few moves to catch that particular pokemon I see on the map"  but what if the bot is 3 blocks away? according to pokevision spawn data,  the timer is not super long on spawn. I still think the better solution is waiting after that integrated webserver, then we can add feature to the map if we want.

**Comment by j-e-k** [comment]
@Jay1 What jay said, develop has a basic api starting. Should be done soon

**Comment by RikudouSage** [comment]
I am a web developer, though I don't do python :( But I can help with the javascript part if someone can prepare good python backend api for me.

**Comment by j-e-k** [comment]
Development has the base for this feature. Closing this to consolidate further web.py work in its own issue
