### ISSUE TITLE
Releasing Duplicates

### ISSUE THREAD

**Issue by dannydotco** [j-e-k/poketrainer#264]
First off, thanks for all the contributions, an amazing bot has been created.

Unfortunately, with the rapid development, decisions have been made that caused continuous confusion and errors. As an example, when the config value `MIN_KEEP_IV` was changed to `KEEP_IV_OVER`, there were no release notes nor any warnings. This in turn made me lose a couple 100% IV pokemon, an 810 CP Eevee being the prime.

With that said, the `RELEASE_DUPLICATES` config flag doesn't really make any sense or offer anything of value. Why should we have to choose between CP and IV?

I propose the following config changes:

```
{
    "MIN_SIMILAR_POKEMON": 1,
    "KEEP_CP_OVER": 1500,
    "KEEP_IV_OVER": 82,
    "RELEASE_DUPLICATES": {
        "GOLBAT": { "RELEASE": "ALWAYS", "UNLESS_CP_OVER": 1800, "UNLESS_IV_OVER": 90 },
        "PIKACHU: { "RELEASE": "NEVER" }
    }
}
```

The above should work as following:

`MIN_SIMILAR_POKEMON: 1`

Keep similar Pokemon of this number _no matter what_.

`KEEP_CP_OVER: 1500`

Keep at least `MIN_SIMILAR_POKEMON` of CP Value > `KEEP_CP_OVER`.

`KEEP_IV_OVER: 82`

Keep at least `MIN_SIMILAR_POKEMON` of IV Value > `KEEP_IV_OVER`.

`RELEASE_DUPLICATES`

Read from this file first. If a GOLBAT is caught, check to see whether or not the above rules are met. If they aren't met, read from the rules in the above config. If the key exists, check to see whether the custom rules are met. First, should we release? `ALWAYS`? If so, is the `UNLESS_CP_OVER` value set and greater? If so, is the `UNLESS_IV_OVER` value set and greater? If all 3 conditions pass, release it.

----

The above changes should give us a much clearer and better understanding over the control of our Pokedex.

----

As an addition, it would be great if the checks could be run after catching a pokemon, so it can be discarded immediately rather than scanning the inventory at specified times.

**Comment by destiny117** [comment]
you should not have lost any pokemons due to config changes. the default values are set so that you never release anything at all...

furthermore the config has changed alot again today, please check the new config.json.example if you update to the lates develpment release.

have you checked the most recent readme which describes the config settings available for releasing? i am positive you can meet your needs with these settings easily

**Comment by dannydotco** [comment]
The latest config definitely has improvements; but I still don't think it gives enough control.

I think we should be able to retain or pokemon on a per pokemon basis.

My Eevee was thrown away because the config would always choose CP > IV when judging what to throw when I had MIN_SIMILAR_POKEMON: 1.

`MIN_SIMILAR_POKEMON` should be separated in to CP, IV and eventually cPM.

Having 1 high CP and 1 high IV is much better than retaining 2 CP, or 2 IV, or 1 CP and 1 CP/IV hybrid.

I'd rather people using the bot have to put in some extra effort to be explicit, like in my example above, and ensure that when a Pokemon is caught, it can determine with 100% accuracy whether or not the bot should keep it. While I appreciate the advancements and the effort put in to these scalar values; I think explicit should be king here.

**Comment by destiny117** [comment]
Check the readme, if you enable the DUPLICATES release method the check for CP and IV values is omitted, it will only score the pokemons based on the SCORE_METHOD, thus this is not the default method
You should not use this, check the CLASSIC release method, it enables you to do exactly what you want

```
      "RELEASE_METHOD": "CLASSIC",
      "RELEASE_METHOD_CLASSIC": {
        "KEEP_CP_OVER": 1000,
        "KEEP_IV_OVER": 90,
        "KEEP_IV_ONLY_WITH_PERCENT_CP": 0,
        "MAX_POKEMON_HIGH_IV": 1
      },
```

should do exactly what you want

**Comment by destiny117** [comment]
Release duplicates is a method that overrides the classic release method. this is something i tried to make more obvious with the new config layout...

ALL options are optional and it will release NOTHING by default, you just have to dig the config (maybe ask if something is unclear) and try to find a solution that works for you.

The config example you provided might work for your use case and be simple enough for that, however it will strip out other functionalities we have that are actively wanted and used. there is no easy way of simplifying the config and still providing all available options.

What you want is somewhat possible now with current options, what doesn't work is making all settings per pokemon type. you can just set "KEEP_POKEMON_NAMES" and "THROW_POKEMON_NAMES"

**Comment by xezero** [comment]
@dannydotco Nice suggestion! If you could implement that in a PR, it would certainly eliminate the need for KEEP_POKEMON_NAMES and THROW_POKEMON_NAMES as well since it would consolidate everything into the RELEASE_DUPLICATES option. I would say instead of "UNLESS_CP_OVER" or "UNLESS_IV_OVER", you change that to "UNLESS_SCORE_OVER" since score can incorporate both CP (well technically LVL, but they're positively correlated) and IV nicely. This way you don't get stuck with a 10 CP but 90 IV or 1000 CP and 10 IV (the computed scores for these would be very low).

**Comment by dannydotco** [comment]
I understand how the current version works, but it's overly complicated and doesn't meet nearly enough use cases.

My proposal is to simply remove all current implementations of releasing Pokemon and replace it with the config example I proposed.

I don't understand what use cases would be missing from the example I posted.

**Comment by dannydotco** [comment]
Unfortunately I don't feel comfortable writing a PR for the bot currently. It moves too rapidly and my Python knowledge is the least of my proficiencies.

If we were to set up a roadmap and cherry pick commits in to daily releases, I'd be okay with that.

**Comment by xezero** [comment]
On a related note, you could accomplish what you want with something like this:

```
"POKEMON_CLEANUP": {
    "RELEASE_METHOD": "DUPLICATES"
}

"RELEASE_METHOD_DUPLICATES": {
      "RELEASE_DUPLICATES_MAX_SCORE": 0.8,
      "RELEASE_DUPLICATES_SCALAR": 0.9
},

"SCORE_METHOD": "FANCY",
 "SCORE_METHOD_FANCY": {
      "WEIGHT_IV": 0.5,
      "WEIGHT_LVL": 0.5
   }
```

I find that this works very nicely to keep all the strongest Pokemon (and those 90% close to it) without having to worry about individual CP or IV values or specifying individual Pokemon's CP/IV values whose CP ranges may vastly be smaller than the other Pokemons (i.e. Magikarps have a low CP range but a 200 CP Magikarp is considered very strong - it would have a very score).

**Comment by destiny117** [comment]
I agree with you @dannydotco, it is still not really simple. but removing the current methods would upset a lot of ppl since I for example don't want to keep a CP1000 / IV10 pokemon, but i want to keep CP a pokemon with IV > 90 as long as it is somewhat close to the best one.

But yes there surely is potential for improvement for simplyfing it while still providing the same + more options.

And i would also find it nice to define some filters based on pokemon type, maybe someone is desperate enough to make a decent PR or maybe i will get desperate enough at times :)

**Comment by dannydotco** [comment]
I think the problem with the current implementations are they are subjective and indeterminate. 

If we make it concrete and pre-determined, every use case can be solved, it just takes a little more work to set up the config. I know for example, I want to keep every EEVEE with IV100, regardless of CV, and I can't accomplish that without keeping every EEVEE no matter what.

**Comment by xezero** [comment]
I'm pretty impressed that you got a 100 IV Pokemon! I think the highest I've ever gotten was only a 97.7 IV.

One interesting to note though isthat even though you can have the same Pokemon with the same IV value, the max CP can often be different, since IV just combines the individual attack, stamina, defense stats with equal weights, while CP is calculated with more bias towards attack.

I believe IV-norm is a better measure of a Pokemon's total potential as it takes into account the attack bias. @destiny117 can correct me here if I'm wrong.

**Comment by dannydotco** [comment]
It keeps even deeper than that though.

I actually have 5 100% IV Pokemon, but I lost my Eevee, which is really the only one I wanted (I have a Dratini already.)

I have a Dragonite with only 80% IV but it has 15/15 STA/DEF, which means it's a great tank for defending gyms, even though it has 7ATK.

I think we need to be able to specify at the very at least which Pokemon not to disregard ever, along with a simpler and more deterministic formula for keeping those you don't explicitly say.

**Comment by xezero** [comment]
I do agree we need a cleaner way to do that. I think a nice simple code change would be to always keep 100 IV in general (they're quite rare anyways, won't clog any boxes), as anything less than that requires the more objective analysis (i.e. individual stats, whether you're using it to attack or defend gyms, etc) - and with the current score method you can sort of keep these candidates around for manual filtering later on.

**Comment by dannydotco** [comment]
With the latest release bot I lost all my 100% IV pokemon except Dratini (because I had that name in the `KEEP_POKEMON_NAMES` config file.)

Just FYI. 

My priority right now is just leveling so I don't care too much, but I think it should be addressed and a final solution determined.

**Comment by destiny117** [comment]
> I think we need to be able to specify at the very at least which Pokemon (by specific ID, not generic name) not to disregard ever
this is actually possible and very simple (though not documented i guess?!?): just mark them as favorites, the bot will never ever throw away favorites

**Comment by xezero** [comment]
@destiny117 That would work so long as the 100% IV pokemon weren't caught during the bot session (since the user hasn't been able to mark them as favorites yet haha).

**Comment by destiny117** [comment]
true but i implied he was referring to specifc single pokemons (not pokemon types), because defining pokemon types is already possible and documented via the KEEP_POKEMON_NAMES

**Comment by dannydotco** [comment]
That is indeed what I meant. And being able to mark as "favorite" or "discard" from the web UI when we have `KEEP_POKEMON_NAMES` set would be great.

**Comment by xezero** [comment]
The web UI has the TRANSFER action at the moment. That might help with discarding the unwanted pokemon kept from KEE_POKEMON_NAMES. Shouldn't be too hard to add FAVORITE.

**Comment by xezero** [comment]
@dannydotco Very quickly created, but would something along the lines of a separate pokemon configuration file like this work?

https://docs.google.com/spreadsheets/d/1J_N1koSpZzq5vkPkBZn10NtQW71BlWHqeptk4lx9WbY/edit?usp=sharing

**Comment by dannydotco** [comment]
I love that idea.

I think though, score is still indeterministic and subjective.

More power would exist if the titles were:

```
name
min_candy_for_evolution
min_iv_to_keep
min_cp_to_keep
min_cpm_to_keep
min_number_to_keep
max_number_to_keep
```

**Comment by xezero** [comment]
Totally! It would be a bit harder to maintain but perfectly valid. If a user empties out any of the columns/fields, we can just ignore them.

**Comment by dannydotco** [comment]
I edited my comment to add some more info.

**Comment by xezero** [comment]
The one thing that would be kinda nice is if we can pull in the absolute max CP for each of the Pokemon depending on trainer level (since it grows) and default the min_cp_to_keep to be a percentage of that. That way if we leave the bot on for a long time, we don't have to worry about going in and changing the min_cp_to_keep values as we encounter higher possible CP Pokemon when we level.

**Comment by dannydotco** [comment]
That would absolutely be better. If we can pull in min/max CP values for those pokemon in to the spreadsheet that would be much better. Also, getting the CPm would be cool, but min/max will take care of that.

**Comment by destiny117** [comment]
Thanks to your contributions @dannydotco we've come to a good state i believe :+1: 

Closing this
