### ISSUE TITLE
Add example range of Score Method Fancy

### ISSUE THREAD

**Issue by joychugh** [j-e-k/poketrainer#268]
Need to add some examples for score method fancy as what can be the possible values here. It is very confusing without it

@destiny117 need your help on this. please add some good examples to readme.

**Comment by xezero** [comment]
Technically the SCORE_METHOD_FANCY variables could be simplified to just having WEIGHT_LVL **or** WEIGHT_IV, and not necessarily both, since the weights have to add up to 1.0 anyways in order for the fancy formula to make sense (the computed scores range from 0 to 1.0 with Pokemon with scores of 1.0 having the most optimal stats):

```
Type: Dragonite CP: 3120, IV: 88.89, Lvl: 33.5, LvlWild: 13.0, MaxCP: 3120, **Score: 0.929747415507**, IV-Norm.: 86
Type: Kabuto CP: 931, IV: 88.89, Lvl: 30.0, LvlWild: 30.0, MaxCP: 986, **Score: 0.910731557051**, IV-Norm.: 93
Type: Magikarp CP: 213, IV: 91.11, Lvl: 29.0, LvlWild: 29.0, MaxCP: 233, **Score: 0.907326076253**, IV-Norm.: 95
Type: Gyarados CP: 2244, IV: 91.11, Lvl: 29.5, LvlWild: 21.0, MaxCP: 2415, **Score: 0.90469860678**, IV-Norm.: 93
Type: Horsea CP: 666, IV: 91.11, Lvl: 30.0, LvlWild: 30.0, MaxCP: 705, **Score: 0.904430671185**, IV-Norm.: 91
Type: Cubone CP: 841, IV: 88.89, Lvl: 30.0, LvlWild: 30.0, MaxCP: 891, **Score: 0.891419912586**, IV-Norm.: 89
Type: Kabutops CP: 1739, IV: 93.33, Lvl: 29.0, LvlWild: 29.0, MaxCP: 1904, **Score: 0.88649220853**, IV-Norm.: 91
Type: Gyarados CP: 2357, IV: 68.89, Lvl: 33.5, LvlWild: 30.0, MaxCP: 2357, **Score: 0.878950725178**, IV-Norm.: 76
Type: Rhyhorn CP: 981, IV: 82.22, Lvl: 30.0, LvlWild: 30.0, MaxCP: 1039, **Score: 0.871247466341**, IV-Norm.: 85
```

**Comment by destiny117** [comment]
I personally don't use it, but i'll try to provide some insight:

It is basically an alternative solution to the CP value, excluding pokemon base stats in the calculation.
This means a Magikarp can have the same score as a Vaporeon, provided that they have the same level and IV.
The pokemons level is compared to its current max possible level (which means player-level +1.5) to get a percentage value. Both values will be weighted according to `WEIGHT_IV` and `WEIGHT_LVL` and are then added up to give the total score.

You could try and get a similar sorting as with CP (within a pokemon type) by setting the `WEIGHT_IV` very low, to something like 0.05

Also if you prefer scores from 0-100 you could multiple the WEIGHT values by 10

It is also not needed that they add up to 1 (or 100 respectively), it just makes more sense

**Comment by destiny117** [comment]
TBH i don't know how to easily describe it in the readme except providing the formula used. zezero is using it as far as i know so he might have better reasoning as to how this feature is useful

**Comment by xezero** [comment]
I would describe it as a Pokemon's desirability score. It's great for sorting and seeing all the most desirable/optimal Pokemon that you have. A great example is that magikarp with a high score, but low CP (since Magikarps can't have very high CP). Sorting by high CP would mask the fact that you have a strong Magikarp (that would evolve to a very strong Gyrados). Same thing goes with any of the Pokemon that have 3 stage evolutions - the first stage CP would generally not be very high.

I also use it exclusively for when releasing duplicates as the score is essentially a normalized combination of it's primary stats (LVL/IV) so I can very easily determine which Pokemon is more desirable.

**Comment by destiny117** [comment]
Closing this, hope this is a bit clearer now. Also check out the new release methods available!
