### ISSUE TITLE
Requirements.txt is different than PoGoMap (in reference to #339)

### ISSUE THREAD

**Issue by HibikiFox** [j-e-k/poketrainer#393]
@j-e-k @infinitewarp @destiny117 
I use PokemonGoMap, and there is a serious conflict in requirements between the bot and the map, if you install one before the other you will end up removing and installing lower versions of protobuf, Jinja2, zerorpc, and then reversing that to install higher versions when running the command `pip install -r requirements.txt` from the bot's requirements - See below for the end result when doing pip from the bot AFTER installing and running pip from PoGoMap

```
Installing collected packages: protobuf, Jinja2, zerorpc
  Found existing installation: protobuf 2.6.1
    Uninstalling protobuf-2.6.1:
      Successfully uninstalled protobuf-2.6.1
  Found existing installation: Jinja2 2.8
    Uninstalling Jinja2-2.8:
      Successfully uninstalled Jinja2-2.8
  Running setup.py develop for zerorpc
Successfully installed Jinja2-2.7.1 protobuf-3.0.0 zerorpc-0.5.2

```
this will break PoGoMap and require you to redo the pip command, and subsequently cause errors in the bot.

Not really a bug but made in reference to #339  since there are discrepancies between the 2 projects in requirements

**Comment by Myhorta** [comment]
Either use virtualenv or docker.

**Comment by rirze** [comment]
If you really wanted, we could fork our own version of PokemonGoMap, without the strict lower version requirements. I'm willing to bet that the project can run off poketrainer dependency requirements.

**Comment by HibikiFox** [comment]
@rirze 
you have it backwards, PokemongoMap uses lower versions, PokeTrainer uses the higher requirements

**Comment by rirze** [comment]
@HibikiFox No, I had it right the first time. What I said before was, even though PokemonGoMap uses lower versions, I'm pretty sure it will fine running off the higher versions specified in poketrainer, meaning that can be compatible if you look past the version requirements.

**Comment by HibikiFox** [comment]
@rirze okay so I miss understood you then Ty ty

**Comment by charredchar** [comment]
I ran into this too when I installed PokemonGoMap AFTER Poketrainer. I ended up just re-running the requirements for Poketrainer and both will run fine side by side.

**Comment by infinitewarp** [comment]
If you are not using something like a virtual environment, you very likely *will* have unexpected problems at some point in the future. Specific dependency versions are pinned in the requirements.txt because those are exactly what we are building and testing against (just like other software projects do with theirs), and we have no certainty of stability if you deviate from them.

Running higher versions of dependencies is *not* always a safe bet. Unexpected upgrades are just as likely to break things as unexpected downgrades.

If you are going to run multiple Python projects, you really need to run them in some kind of environment isolation. Whether that is Docker or virtual environments is up to you (I personally use the latter).
