### ISSUE TITLE
Minimum scan refresh is not 10s

### ISSUE THREAD

**Issue by Nosferatu1922** [j-e-k/poketrainer#405]
Several reports on Reddit saying the scan refresh has increased from 5 seconds to 10 seconds. How does this affect the bot?

Can I change something in config.json, or will an update need to be pushed?

**Comment by infinitewarp** [comment]
I think this is hard-coded to 5 seconds in PGoApi._map_objects_rate_limit, but unfortunately I'm not in a place right now where I can test or submit a fix. Probably should be made configurable too.

**Comment by skydrome** [comment]
nah its changeable, see [nearby_map_objects()](https://github.com/j-e-k/poketrainer/blob/develop/pgoapi/pgoapi.py#L677) and [#L110](https://github.com/j-e-k/poketrainer/blob/develop/pgoapi/pgoapi.py#L110)

**Comment by destiny117** [comment]
For me the 5s rate-limit still works, can you link some references?

**Comment by rirze** [comment]
https://www.reddit.com/r/pokemongodev/comments/4vxseb/psa_7_seconds_scan_delay_is_enough/
It seems like there may or may not be a strict limit to API calls, as suggested by the comments of the linked post. I'd still say the 5s limit is still safe since we are still able to run the bot without any problems.

**Comment by stolencatkarma** [comment]
Looks like the issue has been solved. closing this.
