### ISSUE TITLE
Does transfer in web work for you?

### ISSUE THREAD

**Issue by Simennzz** [j-e-k/poketrainer#489]
I just get sent to the inventory after I click it and the pokemon is not transfered.

**Comment by infinitewarp** [comment]
You do get sent to the inventory page, but if you carefully check your pokemon list again, you should see that the one you selected probably *did* get transferred.

I'd argue that it's a bug that you are redirected to the inventory page instead of the status page after the transfer completes.

**Comment by infinitewarp** [comment]
This should behave better now in the develop branch.

Sometimes freshly-transferred pokémon still show up in the list, though, because web.py is usually looking at a delayed snapshot of your inventory/etc as it's saved periodically to disk by the bot. Modifying that behavior, unfortunately, is a bigger change better suited elsewhere…
