### ISSUE TITLE
Integrate webserver into the bot

### ISSUE THREAD

**Issue by crystalin** [j-e-k/poketrainer#54]
I made a version using websocket to maintain realtime data on the html page (specially cool for the map, which I also changed to be with the pokemon go colors), but because the webserver is using the dump which is only created when we have the GET_INVENTORY, it doesn't feel realtime.

I'd suggest to move the web server into the bot and have the html page being static and downloading the data using Ajax/websocket.

What are your thoughts ?

**Comment by joychugh** [comment]
Would be awesome! Can you do a pull request to develop. You can have the heartbeat update inventory and Pokemon data in pgoapi.py and then just read those objects  instead of calling the real methods to update them. This way the API doesn't have to deal with sleeps and no extra requests are sent to the niantic servers.

**Comment by spamfarm** [comment]
Would suggest just using a `<meta http-equiv="refresh" content="5">` for the time being

**Comment by j-e-k** [comment]
I am working on this in my spare moments ⏳

**Comment by j-e-k** [comment]
A simple messaging system has been started in develop.

**Comment by wesselvdv** [comment]
Any progress on this? Would love to implement a pokemon snipe feature using this.

**Comment by j-e-k** [comment]
Development has the base for this feature. Closing this to consolidate further web.py work in its own issue
