### ISSUE TITLE
Not getting any pokeballs

### ISSUE THREAD

**Issue by grobins** [j-e-k/poketrainer#99]
I'm finding that I don't accumulate any pokeballs, which is strange as the log says the forts are being spinned. Running with these settings...

{
      "auth_service": "google",
      "username": "",
      "password": "",
      "location": "University of Southern California, Los Angeles, CA",
      "USE_GOOGLE": true,
      "GMAPS_API_KEY": "",
      "MIN_KEEP_IV": 50,
      "KEEP_CP_OVER": 100,
      "STEP_SIZE": 400,
      "EXPERIMENTAL": true,
      "SKIP_VISITED_FORT_DURATION": 600,
      "SPIN_ALL_FORTS": true,
      "STAY_WITHIN_PROXIMITY": 500,
      "MIN_ITEMS": {
        "ITEM_POTION": 10,
        "ITEM_SUPER_POTION": 10,
        "ITEM_HYPER_POTION": 10,
        "ITEM_MAX_POTION": 20,
        "ITEM_BLUK_BERRY": 10,
        "ITEM_NANAB_BERRY": 10,
        "ITEM_REVIVE": 10,
        "ITEM_MAX_REVIVE": 10,
        "ITEM_RAZZ_BERRY": 10
      },
      "POKEMON_EVOLUTION": {
        "PIDGEY": 12,
        "WEEDLE":12 
      },
      "MIN_SIMILAR_POKEMON": 1,
      "KEEP_POKEMON_NAMES": ["MEWTWO"],
      "MAX_CATCH_ATTEMPTS": 10
    }

**Comment by Idhanta** [comment]
Same

**Comment by sontek** [comment]
I've also been running out of pokeballs using this one

**Comment by sontek** [comment]
@grobins @Idhanta Can you try this PR?

https://github.com/j-e-k/pgoapi/pull/107/files

**Comment by joychugh** [comment]
If you use experimental feature it will walk along a long route trying to get Pokemon and poleballs and if it says poke stop spinned but no poleballs then you are soft banned

**Comment by sontek** [comment]
@joychugh The problem is it wasn't doing it properly as far as I could tell.  It would fine the nearest and if it was out of range it would just keep walking the normal route.  My PR made it directly walk to to the nearest pokestop to make sure it collects. 

I had it running for ~2hrs and it followed a route that never got within range of a pokestop, it just got close to them.

**Comment by joychugh** [comment]
So that feature was to walk from point A to B with touching all the poke stops in between . The route isigivnn by Google so we have to check every time that did we come across a pokestop or not. If we did spin it. If you make it walk towards not the nearest one then it will not follow the Google route and not reach its destination.

**Comment by joychugh** [comment]
Please try to turn off experimental and "spin all forts" , spin all forts is experimental. Use the Pokestop navigation for now if you find the bot not going close enough to pokestops and i see you are using Stay within vicinity. Please turn that off as well if you want to use "Spin_all_forts"

**Comment by joychugh** [comment]
I would suggest remove "Stay within vicinity" and keep experimental on and spin all forts true.
If still the issue turn them all off.

**Comment by sontek** [comment]
You can also use my PR which makes this feature work perfectly, the branch is here since the PR got closed:

https://github.com/sontek/pgoapi/tree/walk_to_nearest_for_spin

and the updated diff since the PR isn't updating since @joychugh closed it:

https://github.com/j-e-k/pgoapi/compare/master...sontek:walk_to_nearest_for_spin

**Comment by sontek** [comment]
I've been using it and it works exactly as you would expect.  It walks the google maps defined route but wanders off a bit to get closer to pokestops and then wanders back afterwards

**Comment by sontek** [comment]
@joychugh I'm confused on why you are closing all these PRs/issues without discussion.  Do you not want contributions?  Are you planning on fixing this another way?  I don't think blindly closing valid issues + PRs is a nice way to run a community.

I'm willing to work on the PR with feedback if there are things you don't like about it.

**Comment by joychugh** [comment]
Sorry about that I mentioned to stop using google altogether I found a library to make it sure we hit each poke stop without using Google. Its a tiny one that solves the traveling salesman problem without using Google routes since they depend on routes. It'll be a small change there so this won't be needed. I'll try to commit to it soon. Again my apologies. I just wanted to fix it for good and stop using Google since it also needs API keys.

**Comment by Idhanta** [comment]
@joychugh i changed experimental to false and spin all forts to false too, but still doesn't collect poke balls. What value do I put in for stay within proximity to not make it stay within any range, just leave it blank?

**Comment by joychugh** [comment]
put 0  should work

**Comment by grobins** [comment]
@sontek thanks for that PR, looks like a great addition.  My API has limited today, so when it refreshes I will try that PR

**Comment by grobins** [comment]
@sontek @joychugh Seems to be working ok now.  I only changed "STAY_WITHIN_PROXIMITY": 0, and now catching lots of balls.  Had to comment out the CP and XL thresholds on the cleanup script and it was holding on to too many.
